packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@sanity/client": "^7.17.0"
  "@testing-library/jest-dom": "^6.6.0"
  "@testing-library/react": "^16.3.0"
  "@testing-library/user-event": "^14.6.0"
  "@types/node": "^25.4.0"
  "@types/react": "^19.2.14"
  "@types/react-dom": "^19.2.3"
  "@vitejs/plugin-react": "^5.1.4"
  drizzle-kit: "^0.31.9"
  drizzle-orm: "^0.45.1"
  lucide-react: "^0.577.0"
  next: "^16.1.6"
  next-sanity: "^12.1.1"
  next-themes: "^0.4.6"
  react: "^19.2.4"
  react-dom: "^19.2.4"
  sanity: "^5.14.1"
  typescript: "^5.9.3"
  vitest: "^4.0.18"
  zod: "^4.3.6"
