ALTER TABLE "ballots" ALTER COLUMN "user_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "year" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "week" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_1" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_2" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_3" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_4" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_5" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_6" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_7" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_8" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_9" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_10" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_11" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_12" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_13" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_14" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_15" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_16" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_17" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_18" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_19" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_20" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_21" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_22" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_23" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_24" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ballots" ALTER COLUMN "team_25" DROP NOT NULL;