CREATE TABLE IF NOT EXISTS "ballots" (
	"id" serial PRIMARY KEY NOT NULL,
	"userId" varchar(256) NOT NULL,
	"week" integer NOT NULL,
	"year" integer DEFAULT EXTRACT(year FROM CURRENT_DATE) NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp,
	"rank_1" varchar(256) NOT NULL,
	"rank_2" varchar(256) NOT NULL,
	"rank_3" varchar(256) NOT NULL,
	"rank_4" varchar(256) NOT NULL,
	"rank_5" varchar(256) NOT NULL,
	"rank_6" varchar(256) NOT NULL,
	"rank_7" varchar(256) NOT NULL,
	"rank_8" varchar(256) NOT NULL,
	"rank_9" varchar(256) NOT NULL,
	"rank_10" varchar(256) NOT NULL,
	"rank_11" varchar(256) NOT NULL,
	"rank_12" varchar(256) NOT NULL,
	"rank_13" varchar(256) NOT NULL,
	"rank_14" varchar(256) NOT NULL,
	"rank_15" varchar(256) NOT NULL,
	"rank_16" varchar(256) NOT NULL,
	"rank_17" varchar(256) NOT NULL,
	"rank_18" varchar(256) NOT NULL,
	"rank_19" varchar(256) NOT NULL,
	"rank_20" varchar(256) NOT NULL,
	"rank_21" varchar(256) NOT NULL,
	"rank_22" varchar(256) NOT NULL,
	"rank_23" varchar(256) NOT NULL,
	"rank_24" varchar(256) NOT NULL,
	"rank_25" varchar(256) NOT NULL,
	CONSTRAINT "ballots_userId_year_week_unique" UNIQUE("userId","year","week")
);
